spring:
  application:
    name: magiccart
  
  datasource:
    url: jdbc:postgresql://localhost:5432/magiccart
    username: awesome
    password:
    driver-class-name: org.postgresql.Driver
  
  sql:
    init:
      mode: never
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
      continue-on-error: false
  
  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false

# OpenAPI Documentation
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha

# Logging
logging:
  level:
    com.oboco.magiccart: DEBUG
    org.springframework.jdbc: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Server configuration
server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always